server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql

  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true

  redis:
    host: localhost
    port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true
